.TH "run.py" 3 "Fri Dec 18 2020" "Version version 0.1 beta" "SARS-CoV-2 - Machine Learning Drug Hunter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
run.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrun\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrun\&.get_model_by_name\fP (model_name)"
.br
.ti -1c
.RI "def \fBrun\&.get_cmd_line\fP ()"
.br
.ti -1c
.RI "def \fBrun\&.get_scores_list\fP (y_true, y_pred)"
.br
.ti -1c
.RI "def \fBrun\&.get_scores_list_pipeline\fP (X, y, pipe)"
.br
.ti -1c
.RI "def \fBrun\&.get_mean_scores\fP (X, y, scaler, model)"
.br
.ti -1c
.RI "def \fBrun\&.get_scores\fP (X, y, model_name, subset, trainset, scaler, activity_label)"
.br
.ti -1c
.RI "def \fBrun\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SARS-CoV-2 - Machine Learning Drug Hunter from the source code\&.
