.TH "run_KFold" 3 "Fri Dec 18 2020" "Version version 0.1 beta" "SARS-CoV-2 - Machine Learning Drug Hunter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
run_KFold \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_model_by_name\fP (model_name)"
.br
.ti -1c
.RI "def \fBget_cmd_line\fP ()"
.br
.ti -1c
.RI "def \fBget_scores_list\fP (y_true, y_pred)"
.br
.ti -1c
.RI "def \fBget_scores_list_KFold\fP (X, y, pipe)"
.br
.ti -1c
.RI "def \fBget_mean_scores\fP (X, y, scaler, model)"
.br
.ti -1c
.RI "def \fBget_scores\fP (X, y, model_name, subset, trainset, scaler, activity_label)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def run_KFold\&.get_cmd_line ()"

.PP
Definition at line 35 of file run_KFold\&.py\&.
.SS "def run_KFold\&.get_mean_scores ( X,  y,  scaler,  model)"

.PP
Definition at line 87 of file run_KFold\&.py\&.
.SS "def run_KFold\&.get_model_by_name ( model_name)"

.PP
Definition at line 9 of file run_KFold\&.py\&.
.SS "def run_KFold\&.get_scores ( X,  y,  model_name,  subset,  trainset,  scaler,  activity_label)"

.PP
Definition at line 102 of file run_KFold\&.py\&.
.SS "def run_KFold\&.get_scores_list ( y_true,  y_pred)"

.PP
Definition at line 55 of file run_KFold\&.py\&.
.SS "def run_KFold\&.get_scores_list_KFold ( X,  y,  pipe)"

.PP
Definition at line 73 of file run_KFold\&.py\&.
.SS "def run_KFold\&.main ()"

.PP
Definition at line 121 of file run_KFold\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SARS-CoV-2 - Machine Learning Drug Hunter from the source code\&.
