.TH "write_jobs.py" 3 "Fri Dec 18 2020" "Version version 0.1 beta" "SARS-CoV-2 - Machine Learning Drug Hunter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
write_jobs.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBwrite_jobs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwrite_jobs\&.get_model_names\fP ()"
.br
.ti -1c
.RI "def \fBwrite_jobs\&.get_combinations\fP (descriptor_list)"
.br
.ti -1c
.RI "def \fBwrite_jobs\&.write_job\fP (job_id, model_name, subset, trainset, activity_label, cwd, data_file, args)"
.br
.ti -1c
.RI "def \fBwrite_jobs\&.write_all\fP (combinations, model_list, trainset, cwd, data_file, args)"
.br
.ti -1c
.RI "def \fBwrite_jobs\&.get_cmd_line\fP ()"
.br
.ti -1c
.RI "def \fBwrite_jobs\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SARS-CoV-2 - Machine Learning Drug Hunter from the source code\&.
