.TH "write_jobs" 3 "Fri Dec 18 2020" "Version version 0.1 beta" "SARS-CoV-2 - Machine Learning Drug Hunter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
write_jobs \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_model_names\fP ()"
.br
.ti -1c
.RI "def \fBget_combinations\fP (descriptor_list)"
.br
.ti -1c
.RI "def \fBwrite_job\fP (job_id, model_name, subset, trainset, activity_label, cwd, data_file, args)"
.br
.ti -1c
.RI "def \fBwrite_all\fP (combinations, model_list, trainset, cwd, data_file, args)"
.br
.ti -1c
.RI "def \fBget_cmd_line\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def write_jobs\&.get_cmd_line ()"

.PP
Definition at line 70 of file write_jobs\&.py\&.
.SS "def write_jobs\&.get_combinations ( descriptor_list)"

.PP
Definition at line 13 of file write_jobs\&.py\&.
.SS "def write_jobs\&.get_model_names ()"

.PP
Definition at line 9 of file write_jobs\&.py\&.
.SS "def write_jobs\&.main ()"

.PP
Definition at line 81 of file write_jobs\&.py\&.
.SS "def write_jobs\&.write_all ( combinations,  model_list,  trainset,  cwd,  data_file,  args)"

.PP
Definition at line 53 of file write_jobs\&.py\&.
.SS "def write_jobs\&.write_job ( job_id,  model_name,  subset,  trainset,  activity_label,  cwd,  data_file,  args)"

.PP
Definition at line 28 of file write_jobs\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SARS-CoV-2 - Machine Learning Drug Hunter from the source code\&.
